### ISSUE TITLE
Setting as default browser not easy in Win 10, Chrome does it better

### ISSUE THREAD

**Issue by sean-cliqz** [cliqz-oss/browser-f#75]
When installing the CLIQZ browser on Windows 10, I first get this dialog:
![2015-11-30 14 22 02](https://cloud.githubusercontent.com/assets/6603366/11507597/0dcc847c-9855-11e5-8d3e-1c2d6928740c.jpg)

When clicking 'Use CLIQZ as my default browser', it loads this settings page for setting the default app for several different kinds of apps:
![2015-11-30 14 21 50](https://cloud.githubusercontent.com/assets/6603366/11507616/2468ac38-9855-11e5-9cda-c73b7a7575d8.jpg)

The option to set the default browser is at the bottom (below the fold) and requires a couple more clicks to complete the action.

In contrast, when install the Chrome browser, and requesting to make it the default browser, I get this setting directly:
![2015-11-30 14 26 32](https://cloud.githubusercontent.com/assets/6603366/11507659/5fd4af74-9855-11e5-8e96-8c4db1d78d6e.jpg)

I suggest we use the same method as Chrome, as it directly takes the user to default browser setting.

**Comment by alver-cliqz** [comment]
Comments from Chromium source code about how to do a "trick" with default browser:
// On Windows 10+, there is no official way to prompt the user to set a
 // default browser. This is the workaround:
 // 1. Unregister the default browser.
 // 2. Open "How to make Chrome my default browser" link with openwith.exe.
 // 3. Windows will prompt the user with "How would you like to open this?".
 // 4. If Chrome is selected, we intercept the attempt to open the URL and
 //    instead call OnSetAsDefaultAttemptComplete(), passing true to indicate
 //    success.
 // 5. If Chrome is not selected, the url is opened in the selected browser.
 //    After two minutes, we notify the observer that the process failed.

**Comment by alver-cliqz** [comment]
Chromium commit with this fix: https://chromium.googlesource.com/chromium/src.git/+/f89ac7c739d5b0ba039af8cabac76a74ff3b2b54

**Comment by alver-cliqz** [comment]
Similar fix in FF https://bugzilla.mozilla.org/show_bug.cgi?id=1172724
Must work since F 41, but doesn't work

**Comment by alver-cliqz** [comment]
Research result:
1. Firefox create patch to set default browser in Win10 as Sean suggest (and Chrome doing now) in the middle of June. This is was a patch (https://bugzilla.mozilla.org/show_bug.cgi?id=1172724,) to 41-th version, and FF team decide to do A/B test in version 40.0.1 (https://bugzilla.mozilla.org/show_bug.cgi?id=1172724#c14)
2. After A/B test (?) they decide to use previous solution with default system "Settings" dialog. Reason is unclear: https://bugzilla.mozilla.org/show_bug.cgi?id=1183682. May be some useful information here: https://bugzilla.mozilla.org/show_bug.cgi?id=1193395

At least we can try to turn this feature back in our build and look how it's work.

**Comment by stefanie-cliqz** [comment]
Will set up support page for this matter on cliqz.com/support next week. (content of page see: https://support.mozilla.org/en-US/kb/how-change-your-default-browser-windows-10

**Comment by alver-cliqz** [comment]
Some information about how this work. "Open as" dialog use protocol handlers (they are store in registry). It define which application to use to process protocol or file extensions). For browser it means which one of installed in system will open an http or https.

So, to change this handler we use "Open As" dialog with https parameters. This action will show a next dialog window:
![openas](https://cloud.githubusercontent.com/assets/14071898/12203882/917a408a-b631-11e5-9ba2-4171924a8a5b.jpg)

This is OS dialog. It is modal and lost focus if user click outside. Pay attention to "Always use this app" checkbox. This could be not checked, because system have some handler for this protocol. IMO, it is not good to clean up this handler (as Chrome do) because user can cancel this dialog and the OS could fall into strange state. So, more research need here.

Next problem - "Options" screen in FF. If user change handler to our browser this is do NOT make browser default on system level. FF try do detect a default browser on system level and reflect state on this page. That's why we still see next picture, browser not default, only protocol handler point to FF:
![default](https://cloud.githubusercontent.com/assets/14071898/12204195/17f3feb6-b633-11e5-9a95-b1b5c89f5e61.jpg)

IMO, better to do some more investigation about this and improve all aspects for Win10.

**Comment by alver-cliqz** [comment]
https://github.com/cliqz-oss/browser-f/pull/107

**Comment by luciancor** [comment]
After the installation of CLIQZ browser, Win10 asks the user "how do you want to open this?", by clicking on “CLIQZ” a new tab is opened in the CLIQZ browser (see screenshot)
![screen shot 2016-01-14 at 17 19 45](https://cloud.githubusercontent.com/assets/5583036/12349311/ea9f337c-bb6e-11e5-9b17-ea27af45402d.png)

**Comment by chrmod** [comment]
moved to jira
