### ISSUE TITLE
Linux platform support?

### ISSUE THREAD

**Issue by RoPe93** [cliqz-oss/browser-f#840]
Why not for Linux? I doubt there is any technical problem to have Linux version since Mac, Windows, Android and iOS versions are supported.

**Comment by alver-cliqz** [comment]
Good day.

We have an unofficial build for Linux, you can find detailed information here: https://cliqz.com/en/desktop/cliqz-for-linux. We are not testing Linux build, so, there are might be some problems in it. Also there is Archlinux package, built by cliqz fans.

**Comment by chrmod** [comment]
@RoPe93 we are also happy to welcome any kind of contribution that can help us to support the Linux builds. In a way supporting Linux versions is much harder than Window or MacOS due to variety of GNU/Linux distributions. Back in a day we have tried distribution agnostic packaging systems jak snap and appimage, but those have their own quirks. Please note that Cliqz is a very small team (compared to other browser vendors), thus our possibility to support niche markets is limited - that said we have a lot of passion for Linux and Open Source in general. BTW. you can always build cliqz browser from source :-)
